// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `INSERT INTO users (name, dob) VALUES (?, ?)`

type CreateUserParams struct {
	Name string
	Dob  time.Time
}

// CreateUser inserts a row and returns the full User by fetching it via LastInsertId.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	result, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.Dob)
	if err != nil {
		return User{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return User{}, err
	}
	return q.GetUserByID(ctx, int32(id))
}

const getUserByID = `SELECT id, name, dob FROM users WHERE id = ?`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const updateUser = `UPDATE users SET name = ?, dob = ? WHERE id = ?`

type UpdateUserParams struct {
	Name string
	Dob  time.Time
	ID   int32
}

// UpdateUser updates a row and returns it. Returns sql.ErrNoRows when id is not found.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	result, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Dob, arg.ID)
	if err != nil {
		return User{}, err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return User{}, err
	}
	if affected == 0 {
		return User{}, sql.ErrNoRows
	}
	return q.GetUserByID(ctx, arg.ID)
}

const deleteUser = `DELETE FROM users WHERE id = ?`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const listUsers = `SELECT id, name, dob FROM users ORDER BY id LIMIT ? OFFSET ?`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countUsers = `SELECT COUNT(*) FROM users`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
